[phases.setup]
nixPkgs = ['gcc', 'sqlite', 'python39']

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn ping_pong_web:app"
